rename Gtk -> Ctk

diff --git a/Makefile.decl b/Makefile.decl
--- a/Makefile.decl
+++ b/Makefile.decl
@@ -23,7 +23,7 @@ SKIP_GDKTARGET = \
 	false
 else
 SKIP_GDKTARGET = \
-	echo "Gtk+Tests:INFO: Skipping GUI tests for non-X11 target."
+	echo "Ctk+Tests:INFO: Skipping GUI tests for non-X11 target."
 endif
 
 if PLATFORM_WIN32
@@ -35,7 +35,7 @@ XVFB_START = \
 	&& XID=`for id in $(XIDS) ; do test -e /tmp/.X$$id-lock || { echo $$id; exit 0; }; done; exit 1` \
 	&& { ${XVFB} :$$XID -nolisten tcp -auth /dev/null >/dev/null 2>&1 & \
 	       trap "kill -15 $$! " 0 HUP INT QUIT TRAP USR1 PIPE TERM ; } \
-	|| { echo "Gtk+Tests:ERROR: Failed to start Xvfb environment for X11 target tests."; exit 1; } \
+	|| { echo "Ctk+Tests:ERROR: Failed to start Xvfb environment for X11 target tests."; exit 1; } \
 	&& DISPLAY=:$$XID && export DISPLAY
 # call as: $(XVFB_START) && someprogram
 
